Add error context to filesystem errors
Rust does not give any context to errors in std::fs. So when first
running this program I got:

	Error: No such file or directory (os error 2)

Adding context now gives:

	Error: failed to read directory /etc/archdiff/ignore

	Caused by:
	    No such file or directory (os error 2)

This helps me and hopefully others figure out where fs errors occure.